apiVersion: v1
kind: Service
metadata:
  name: nodeapp-example
  namespace: old
  labels:
    app: node1
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: node